# Given: I want to use Merge Queue
# Given: I don't want to have to run tests twice (default behavior is to require passing tests before adding to the merge queue, then run them again in the merge queue)
# Given: I always want tests to run and pass before the PR is merged to main, unless I explicitly grant an exemption
# Given: I want to grant an exemption to allow tests to be skipped if the PR consists of only changes to files with extension ".md"

# When: Events with name "pull_request" happen
# Then: Immediately report success

# When: Events with name "merge_group" happen
# And: The PR meets the criteria for granting an exemption
# Then: Immediately report success

# When: Events with name "merge_group" happen
# And: The PR does not meet the criteria for granting an exemption
# Then: Run the tests

on:
  pull_request:
  merge_group:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  skip-tests-if-pull-request-event:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: skip-tests-if-pull-request-event
        # noinspection YAMLSchemaValidation
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/report-status-context@main
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          status-check: test / e2e-on-prem-lite
          status: success
          description: "Tests skipped because this is a pull_request event"

  skip-tests-if-merge-group-event-and-exemption-criteria-met:
    if: |
      github.event_name == 'merge_group' &&
      github.event.client_payload.pull_request.files.every(file => file.filename.endsWith('.md'))
    runs-on: ubuntu-latest
    steps:
      - name: skip-tests-if-merge-group-event-and-exemption-criteria-met
        # noinspection YAMLSchemaValidation
        uses: defenseunicorns/delivery-github-actions-workflows/.github/actions/report-status-context@main
        with:
          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
          status-check: test / e2e-on-prem-lite
          status: success
          description: "Tests skipped because this is a merge_group event and the PR meets the criteria for granting an exemption"

#  e2e-on-prem-lite:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout Repo
#        uses: actions/checkout@v4
#      - name: Run E2E Tests
#        uses: ./.github/actions/e2e
#        with:
#          application_id: ${{ secrets.NARWHAL_BOT_APP_ID }}
#          application_private_key: ${{ secrets.NARWHAL_BOT_SECRET }}
#          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
#          region: us-east-1
#          github-context: "test / e2e-on-prem-lite"
#          test-to-run: "on-prem-lite"
