# If the workflow trigger is "merge_group", run the automated tests.

name: merge-group-test

on:
  merge_group:
  pull_request:

permissions:
  id-token: write
  contents: read

defaults:
  run:
    # We need -e -o pipefail for consistency with GitHub Actions' default behavior
    shell: bash -e -o pipefail {0}

jobs:
  e2e-on-prem-lite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Run E2E Tests
        uses: ./.github/actions/e2e
        with:
          token: ${{ secrets.PAT }}
          role-to-assume: ${{ secrets.AWS_COMMERCIAL_ROLE_TO_ASSUME }}
          github-context: "test / e2e-on-prem-lite"
          test-to-run: "on-prem-lite"
