# If the workflow trigger is "pull_request" or "merge_group", run the pre-commit checks.
# Also run it on pushes to main, so that caches are created from the main branch, which will let child branches use them

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Init Cache
        uses: ./.github/actions/cache
      - name: Init pre-commit cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.cache/pre-commit"
          key: "pre-commit|common|${{hashFiles('.env')}}|${{hashFiles('.pre-commit-config.yaml')}}"
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: common

  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Init Cache
        uses: ./.github/actions/cache
      - name: Init pre-commit cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.cache/pre-commit"
          key: "pre-commit|terraform|${{hashFiles('.env')}}|${{hashFiles('.pre-commit-config.yaml')}}"
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: terraform

  golang:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Init Cache
        uses: ./.github/actions/cache
      - name: Init pre-commit cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.cache/pre-commit"
          key: "pre-commit|golang|${{hashFiles('.env')}}|${{hashFiles('.pre-commit-config.yaml')}}"
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: golang

  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Init Cache
        uses: ./.github/actions/cache
      - name: Init pre-commit cache
        uses: actions/cache@v3
        with:
          path: "${{ github.workspace }}/.cache/pre-commit"
          key: "pre-commit|renovate|${{hashFiles('.env')}}|${{hashFiles('.pre-commit-config.yaml')}}"
      - name: pre-commit
        uses: ./.github/actions/pre-commit
        with:
          check-type: renovate
